annotations: {}

image: "vpa-manager:latest"
imagePullPolicy: IfNotPresent

podAnnotations: {}

## Assign a PriorityClassName to pods if set
# priorityClassName: ""

resources: {}

serviceAccount:
  annotations: {}

targetNamespaces: []
