## Affinity settings for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
affinity: {}

annotations: {}

image:
  pullPolicy: IfNotPresent
  repository: "vpa-manager"
  tag: "latest" 

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

podAnnotations: {}

## Assign a PriorityClassName to pods if set
# priorityClassName: ""

resources: {}

# Configuration for what resources to create Vertical Pod autoscalers for
# Setting the configuration option to False will ignore the resource type completely
resourcesToManage:
  cronjobs: "True"
  deployments: "True"
  jobs: "True"
  pods: "True"

# Number of old history to retain to allow rollback
# Default Kubernetes value is set to 10
revisionHistoryLimit: 10

serviceAccount:
  annotations: {}

# List of namespaces to create Vertical Pod Autoscaler resources for
# Leaving this empty will create VPA resources for all namespaces
targetNamespaces: []


## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
