## Affinity settings for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
affinity: {}

## Annotation values for deployment resource
deploymentAnnotations: {}

image:
  pullPolicy: IfNotPresent
  repository: "vpa-manager"
  tag: "latest" 

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Annotation values for pod resource
podAnnotations: {}

## Assign a PriorityClassName to pods if set
# priorityClassName: ""

## Define the resources the controller container needs
## These are not set by default as the controller will create a VPA for itself
resources: {}

# Configuration for what resources to create Vertical Pod autoscalers for
# Setting the configuration option to False will ignore the resource type completely
resourcesToManage:
  cronjobs: "True"
  deployments: "True"
  jobs: "True"
  pods: "True"

# Number of old history to retain to allow rollback
# Default Kubernetes value is set to 10
revisionHistoryLimit: 10

## Annotation values for service account resource
serviceAccountAnnotations: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Parameter to control which mode each Vertical Pod Autoscaler resource will have
# Options are: Auto, Recreate, Initial and Off
## Ref: https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
updateMode: "Off"

# List of namespaces to create Vertical Pod Autoscaler resources for
# Leaving this empty will create VPA resources for all namespaces
watchedNamespaces: []
