apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa-manager.labels" . | indent 4 }}
data:
  WATCHED_NAMESPACES: '{{ .Values.watchedNamespaces | default (list) | join "," }}'
  {{- range $name, $value := .Values.resourcesToManage }}
  ENABLE_{{ $name | upper }}: {{ $value | quote }}
  {{- end }}
