apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa-manager.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vpa-manager.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "vpa-manager.labels" . | indent 8 }}
    spec:
      containers:
        - name: vpa-manager
          env:
            - name: TARGET_NAMESPACES
              value: '{{ .Values.targetNamespaces | default (list) | join "," }}'
          image: vpa-manager:latest
          imagePullPolicy: IfNotPresent
      serviceAccountName: {{ .Release.Name }}
