apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa-manager.labels" . | indent 4 }}
  {{- if .Values.serviceAccountAnnotations }}
  annotations:
    {{ toYaml .Values.serviceAccountAnnotations | indent 4 }}
  {{- end }}
