on:
  workflow_call:
    inputs:
      tagged_version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  package-and-publish-chart:
    name: Package and Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tagged_version }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Package Helm Chart
        run: helm package ./chart --destination ./chart-package

      - name: Create Helm Repo Index
        run: helm repo index ./chart-package --url https://jcluppnow.github.io/vpa-manager

      - name: Copy README to be published alongisde Helm chart
        run:  cp ./chart/index.md ./chart-package

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          enable_jekyll: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./chart-package
