name: PR checks

on: [pull_request]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          tags: quay.io/jcluppnow/vpa-manager:latest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Lint Go files
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Tests
        run: go test -v ./...

  # This job must pass to merge a PR, allows us to add and remove PR checks as required.
  required:
    name: PR Checks Completed
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR Checks Completed"
