name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    uses: ./.github/workflows/tag.yaml

  build-and-publish:
    needs: tag
    secrets: inherit
    uses: ./.github/workflows/build-and-publish-image.yaml
    with:
      tagged_version: ${{ needs.tag.outputs.taggedVersion }}

  package-and-publish-chart:
    needs: tag
    uses: ./.github/workflows/package-and-publish-chart.yaml
    with:
      tagged_version: ${{ needs.tag.outputs.taggedVersion }}
